# To verify this file, call `travis lint .travis.yml` with travis-cli gem installed. To install, call `bundle install` in this directory.
# To make life easier, I made a git commit hook to run this after each commit for reference. Create a file: `.git/hooks/pre-commit` and put inside (without the '#' before the line):
# echo "----linting .travis.yml----"
# travis lint .travis.yml
# exit 0

os: osx
osx_image: xcode9.3
language: swift
before_install:
#- gem install cocoapods --pre # update cocoapods to newest version.
- pod repo update
install:
  - bundle install
  - (cd Example/ && pod install)
cache:
  directories:
    - $HOME/.rvm/gems
    - $HOME/.cocoapods

jobs:
  include:
    - stage: danger
      script: bundle exec danger
    - stage: pr
      script: pod spec lint --verbose --allow-warnings;./Example/Pods/SwiftLint/swiftlint --config Example/.swiftlint.yml

stages:
  - name: danger
    if: type IN (pull_request)
  - name: pr
    if: type IN (pull_request)
